// @ts-ignore
import { Hotel, Booking, User } from '@/types';

export const MOCK_HOTELS: Hotel[] = [
  {
    id: '1',
    name: 'The Alila Diwa Sanctuary',
    location: 'Majorda, South Goa',
    state: 'Goa',
    price: 850,
    rating: 4.9,
    reviews: 1200,
    image: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80',
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80',
      'https://images.unsplash.com/photo-1582610116397-edb72f7b6e28?w=800&q=80',
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80',
    ],
    tags: ['Coastal Escape', 'Romantic', 'Wellness'],
    mood: ['Deep Rest', 'Romantic Escape'],
    description:
      'Nestled amidst the lush paddy fields of South Goa, The Alila Diwa Sanctuary is a masterpiece of minimalist contemporary architecture. Designed as an extension of the Goan landscape, the property utilizes local materials like red laterite stone and teak wood to create a dialogue between structure and nature.',
    amenities: [
      'Infinity Pool',
      'Ayurvedic Spa',
      'Private Beach',
      'Michelin Dining',
      'Yoga Pavilion',
      'Butler Service',
    ],
    featured: true,
    aiMatch: 98,
  },
  {
    id: '2',
    name: 'The Ethereal Atoll',
    location: 'North Malé Atoll, Maldives',
    state: 'Maldives',
    price: 2030,
    rating: 5.0,
    reviews: 890,
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
      'https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=800&q=80',
    ],
    tags: ['Overwater', 'Romantic', 'Luxury'],
    mood: ['Romantic Escape', 'Deep Rest'],
    description:
      "An otherworldly collection of overwater villas suspended above the Indian Ocean's clearest lagoon. Each villa features a glass-floor panel, direct ocean access, and 270-degree water views.",
    amenities: [
      'Private Plunge Pool',
      'Underwater Restaurant',
      'Coral Restoration Program',
      'Seaplane Transfer',
    ],
    featured: true,
    aiMatch: 95,
  },
  {
    id: '3',
    name: 'Cresta Palace Residence',
    location: 'St. Moritz, Switzerland',
    state: 'Switzerland',
    price: 1460,
    rating: 4.8,
    reviews: 450,
    image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80'],
    tags: ['Mountain Retreat', 'Ski-In/Ski-Out', 'Luxury'],
    mood: ['Adventure Seeking', 'Deep Rest'],
    description:
      'Perched at 1,800 metres in the Engadin valley, Cresta Palace is a living monument to Belle Époque architecture and Alpine grandeur.',
    amenities: [
      'Ski Concierge',
      'Heated Outdoor Pool',
      'Michelin Dining',
      'Spa & Wellness',
      'Helipad',
    ],
    featured: false,
    aiMatch: 88,
  },
  {
    id: '4',
    name: 'Kyoto Silent Monolith',
    location: 'Arashiyama, Kyoto',
    state: 'Japan',
    price: 1100,
    rating: 4.9,
    reviews: 320,
    image: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80'],
    tags: ['Zen', 'Architecture', 'Cultural'],
    mood: ['Quiet Contemplation', 'Deep Rest'],
    description:
      "A marvel of minimalist architecture nested in the heart of Kyoto's Arashiyama forests. Designed around silences and the philosophy of Ma.",
    amenities: ['Private Zen Garden', 'Kaiseki Dining', 'Forest Meditation', 'Tea Ceremony'],
    featured: true,
    aiMatch: 99,
  },
  {
    id: '5',
    name: 'The Ranthambore Haveli',
    location: 'Ranthambore, Rajasthan',
    state: 'Rajasthan',
    price: 650,
    rating: 4.7,
    reviews: 280,
    image: 'https://images.unsplash.com/photo-1596436280045-47fc99c8a336?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1596436280045-47fc99c8a336?w=800&q=80'],
    tags: ['Heritage', 'Wildlife', 'Cultural'],
    mood: ['Wild Adventure', 'Cultural Immersion'],
    description:
      'A restored 19th-century haveli on the edge of Ranthambore National Park, offering private tiger safaris and Rajasthani folk evenings under the stars.',
    amenities: ['Private Safari', 'Heritage Rooms', 'Rooftop Dining', 'Cultural Evenings'],
    featured: false,
    aiMatch: 85,
  },
  {
    id: '6',
    name: 'Singular Patagonia',
    location: 'Puerto Natales, Patagonia',
    state: 'Chile',
    price: 980,
    rating: 4.8,
    reviews: 210,
    image: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800&q=80'],
    tags: ['Adventure', 'Nature', 'Remote'],
    mood: ['Wild Adventure', 'Quiet Contemplation'],
    description:
      'Converted from a 1914 cold-storage plant, this industrial-chic property overlooks the Last Hope Sound and serves as a gateway to Torres del Paine.',
    amenities: ['Trekking Guides', 'Kayaking', 'Historic Architecture', 'Locally Sourced Dining'],
    featured: false,
    aiMatch: 82,
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    hotelId: '2',
    hotelName: 'The Ethereal Atoll',
    location: 'North Malé Atoll, Maldives',
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
    checkIn: '2024-12-12',
    checkOut: '2024-12-19',
    nights: 7,
    guests: 2,
    total: 14200,
    status: 'confirmed',
  },
  {
    id: 'b2',
    hotelId: '3',
    hotelName: 'Cresta Palace Residence',
    location: 'St. Moritz, Switzerland',
    image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80',
    checkIn: '2025-01-14',
    checkOut: '2025-01-18',
    nights: 4,
    guests: 2,
    total: 5850,
    status: 'pending',
  },
  {
    id: 'b3',
    hotelId: '4',
    hotelName: 'Kyoto Silent Monolith',
    location: 'Arashiyama, Kyoto',
    image: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
    checkIn: '2024-10-01',
    checkOut: '2024-10-07',
    nights: 6,
    guests: 1,
    total: 6600,
    status: 'completed',
  },
];

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Julian Vane',
  email: 'julian@nestiq.com',
  tier: 'Elite',
  memberSince: '2021',
  bio: 'Seeking architectural landmarks and quiet luxury retreats.',
  preferences: 'Preferred climate: Temperate. Dietary: Plant-focused fine dining.',
};

export const VIBES = [
  'Coastal Escape',
  'Urban Minimalism',
  'Mountain Retreat',
  'Jungle & Forest',
  'Desert Oasis',
  'Heritage & Cultural',
];
export const MOODS = [
  'Quiet Contemplation',
  'Social Energy',
  'Wild Adventure',
  'Deep Rest',
  'Romantic Escape',
  'Cultural Immersion',
];
